- Lib/defcon/objects/contour.py
> contour: fix points undo methods calls

- Lib/defcon/objects/contour.py
- Lib/defcon/objects/features.py
- Lib/defcon/objects/font.py
- Lib/defcon/objects/glyph.py
- Lib/defcon/objects/layer.py
- Lib/defcon/objects/layerSet.py
- Lib/defcon/objects/layoutEngine.py
- Lib/defcon/tools/notifications.py
Mostly #41 followup.
r? @typesupply
> Clean things up

- Lib/defcon/objects/font.py
I needed to add these to make it work.
> Couple of missing self. statements

- Lib/defcon/tools/representations.py
> representations: always close path in AreaPen

- Lib/defcon/objects/contour.py
Like #62 but for master branch.
> [master] always close path in AreaPen

- Lib/defcon/objects/imageSet.py
Makes things work with py3 and restore old behavior on py2 (before py23).
r? @typesupply
> imageSet: fix string encoding

- Lib/defcon/objects/contour.py
- Lib/defcon/objects/imageSet.py
(Branched on top of #67.)
Fixes #68.
r? @typesupply
> contour: forward move in removeSegment

- Lib/defcon/objects/glyph.py
- Lib/defcon/test/objects/test_glyph.py
- add glyph.verticalOrigin
- use or set glyph.verticalOrigin with glyph.topMargin and glyph.bottomMargin
> Add glyph.verticalOrigin

- Lib/defcon/objects/contour.py
> Contour: pass kwargs to point class

- Lib/defcon/objects/color.py
- Lib/defcon/objects/layerSet.py
- Lib/defcon/test/objects/test_color.py
As slicing makes a copy.
r? @typesupply
> Use more iterators

- Lib/defcon/objects/layoutEngine.py
> LayoutEngine: also set advanceHeight

- Lib/defcon/objects/groups.py
- Lib/defcon/objects/kerning.py
- Lib/defcon/test/objects/test_groups.py
- Lib/defcon/test/objects/test_kerning.py
- Lib/defcon/tools/representations.py
> Implement find method in the kerning object.

- Lib/defcon/objects/glyph.py
> adding the contour and componet while sending an added notification

- Lib/defcon/objects/glyph.py
- Lib/defcon/test/objects/test_glyph.py
> Change how `glyph.unicode` behaves

- Lib/defcon/objects/glyph.py
Adds notifications for:
`Glyph.LeftMarginWillChange`
`Glyph.LeftMarginDidChange`
`Glyph.RightMarginWillChange`
`Glyph.RightMarginDidChange`
`Glyph.TopMarginWillChange`
`Glyph.TopMarginDidChange`
`Glyph.BottomMarginWillChange`
`Glyph.BottomMarginDidChange`
> Adds more notifications before/after glyph margins change

- Lib/defcon/tools/bezierMath.py
in the combo line curve or curve line only join and preserve if the angle the line and associated handles is smaller then 30 degrees
> improve joinSegments

- Lib/defcon/pens/transformPointPen.py
> add identifier to addComponent callback

- Lib/defcon/objects/font.py
- Lib/defcon/objects/layerSet.py
- Lib/defcon/test/objects/test_font.py
see https://github.com/fonttools/fonttools/pull/1786#issuecomment-633271602
> move to UFOFormatVersion as a tuple

- Lib/defcon/objects/glyph.py
+ post willBeAdded notifcations for anchor and guidelines with the guideline as data object
> instantiate anchor and guidelin with glyph attribute

- Lib/defcon/objects/contour.py
- Lib/defcon/test/objects/test_contour.py
> Dont pop and extend to last segment when there are only quad off curves

- Lib/defcon/objects/anchor.py
- Lib/defcon/objects/base.py
- Lib/defcon/objects/glyph.py
- Lib/defcon/objects/guideline.py
- Lib/defcon/test/objects/test_font.py
- Lib/defcon/test/objects/test_glyph.py
> add support for __eq__ in a BaseDict

- Lib/defcon/objects/glyph.py
- Lib/defcon/objects/image.py
+ Add notification before and after an image is being cleared
> Make the glyph.image object sticky just like lib objects

- Lib/defcon/objects/guideline.py
- Lib/defcon/test/objects/test_guideline.py
> when guideline.name is set to None remove the name key

- Lib/defcon/test/tools/test_fuzzyNumber.py
- Lib/defcon/tools/fuzzyNumber.py
Improve complex sorting for tuples with a fuzzyNumber
when the numbers is in a certain threshold, mark it as equal 
+ test
> add __eq__ and __hash__ to FuzzyNumber

- Lib/defcon/objects/layerSet.py
the older glyphSet attribute could be already closed
> Create a new glyphset from the provided reader

- Lib/defcon/objects/base.py
> Remove some big memory attributes from all defcon objects on delete

- .github/workflows/run-tests.yml
- Lib/defcon/test/objects/test_dataSet.py
- Lib/defcon/test/objects/test_font.py
- Lib/defcon/test/objects/test_imageSet.py
- Lib/defcon/test/objects/test_layer.py
- Lib/defcon/test/objects/test_layerSet.py
- Lib/defcon/test/testTools.py
- requirements.txt
- setup.py
- tox.ini
replaced all `import fs` with `fontTools.misc.filesystem as fs`
> bump fonttools >= 4.59, remove fs dependency 
