robotools/defcon

documentation/source/concepts/externalchanges.rst
typo: "modification data" => "modification date"
=> [docs] fix typo in "external changes" section

Lib/defcon/objects/component.py, Lib/defcon/objects/contour.py, Lib/defcon/objects/font.py, Lib/defcon/objects/glyph.py, Lib/defcon/pens/decomposeComponentPointPen.py, Lib/defcon/tools/booleanOperations/flatten.py, documentation/source/index.rst, setup.py
This switches defcon to use ufoLib; this works for everything except
that defcon calls on:
robofab.tools.fontlabFeatureSplitter
TransformPointPen
ReverseContourPointPen
The fontLabFeature splitter should likely be re-written somewhere
(fontParts?), and those two pens could be added to ufoLib, but I don’t
know what you want to do with them (new pen module, fontParts, put them
in ufoLib) so I have kept the robofab dependency for defcon for these
things.
=> Updating ufo3 branch of defcon to drop robofab

Lib/defcon/objects/font.py
as reported by @mashabow, `Layer` object only has 'keys' method, and no 'values'.
https://github.com/typesupply/defcon/pull/48/files/a9c0c9f961fcc6064e14c5d629db09fd20b67ca7#r63487919
We can simply `yield` the values by iterating on the layer's `keys()`.
Or we could add a `values()` method to Layers, like this:
E.g.:
```python
def values(self):
return [self[name] for name in self.keys()]
```
=> objects.font: fix __iter__ method raising AttributeError

Lib/defcon/objects/anchor.py, Lib/defcon/objects/guideline.py
a minor issue introduced in 71516c313c1f82cffe66ba1b42b311ec0450b34d
=> fix AttributeError with `self._identifier` on Anchor and Guideline classes

Lib/defcon/objects/glyph.py, Lib/defcon/test/objects/test_anchor.py, Lib/defcon/test/objects/test_component.py, Lib/defcon/test/objects/test_contour.py, Lib/defcon/test/objects/test_imageSet.py, Lib/defcon/test/objects/test_layer.py
Requires https://github.com/unified-font-object/ufoLib/pull/39
* tests: guideline.getParent() can return guideline.font since e87e0c
* tests: use unicode_literals in tests_imageSet
* tests: update identifier tests to match 71516c
* glyph: replace guideline.fontInfo by guideline.font as in e87e0c
=> [ufo3] fix tests and replace guideline.fontInfo by guideline.font

Lib/defcon/objects/glyph.py, Lib/defcon/test/objects/test_glyph.py
When editing fonts for vertical layout one should be able to use glyph.topMargin and glyph.bottomMargin just like they would with glyph.rightMargin or glyph.leftMargin in horizontal layout.
=> objects.glyph: Add topMargin and bottomMargin

Lib/defcon/objects/font.py, Lib/defcon/objects/guideline.py, Lib/defcon/test/objects/test_font.py, Lib/defcon/test/objects/test_layer.py
This patch is similar to 0be21f696422af52984735cf44c4b212e172294a but for font guidelines instead of glyph.
r? @typesupply
=> font: don't set font when instantiating guideline

Lib/defcon/objects/glyph.py
In some cases a guideline may be on top of another, even though this is not good it is valid and shouldn’t raise and AssertionError.
=> glyph: one may insert guidelines with the same x, y or angle

Lib/defcon/objects/layer.py, Lib/defcon/objects/layerSet.py
Instead of converting layer names to unicode just before sending them to ufoLib, I think it's better we ensure they are unicode strings at the time they are set, i.e. in the `_set_name` property setter.
The `tounicode` function uses by default 'ascii' when decoding bytes to unicode. I think it's fine to leave that as is. If users want to set a layer name to anything that non-ascii, then they must use unicode literals (e.g. u"").
For consistency, we should probably do the same (normalizing string input to unicode) for all the other string-y attributes (e.g. glyph.name, etc.).
/cc @typemytype @adrientetar
=> [layer/layerSet] use py23.tounicode(); unicode() built-in is gone in py3

Lib/defcon/objects/layer.py
So that defcon clients can blacklist glyphs as save targets (subclass saveGlyph(), so the glyphs shouldn't be modified individually in the parent function saveLayer()).
r? @anthrotype 
Could you cut a new release with this? I need this change in TruFont. Thx!
=> Layer: dirtify glyphs in saveGlyph(), not in parent saveLayer()

Lib/defcon/objects/layer.py, Lib/defcon/tools/representations.py
I noticed that the `Layer.controlPointBounds` property getter is not using the corresponding `Glyph.controlPointBounds`, but is instead doing the work all by itself for no apparent reason; on the other hand, `Layer.bounds` takes advantage of `Glyph.bounds`.
So I made the two getters consistent with each other, and have the layer's control point bounds be determined directly by the glyphs' ones.
I also noticed that the two functions that are used to compute a glyph's bounds and controlPointBounds (in `representations.py`) are computing again the bound for each component, but that's not necessary, since the fontTools `BoundsPen` and `ControlBoundsPen` inherit from `BasePen`, which has a `addComponent` method that takes care of transforming/drawing the components.
/cc @typesupply …
=> use Glyph.controlPointBounds to calculate Layer.controlPointBounds

Lib/defcon/objects/base.py, Lib/defcon/objects/component.py, Lib/defcon/objects/contour.py, Lib/defcon/objects/dataSet.py, Lib/defcon/objects/font.py, Lib/defcon/objects/glyph.py, Lib/defcon/objects/imageSet.py, Lib/defcon/objects/layer.py, Lib/defcon/objects/layerSet.py, Lib/defcon/objects/point.py, Lib/defcon/test/objects/test_font.py
Previously when a glyph was renamed, defcon would first remove the old name from the glyphOrder then append the new one. This makes rename a single operation so that **a renamed glyph keeps the same position in the glyphOrder.**
Note: this drops the multiple removal passes from removed glyph name, as it's not necessary. The adding code checks that the glyph name isn't already in the glyph order.
Fixes trufont/trufont#314.
r? @anthrotype
=> Font: make rename an atomic glyphOrder op

Lib/defcon/objects/base.py, Lib/defcon/objects/glyph.py, Lib/defcon/objects/layer.py
- add beginUndoGroup()/endUndoGroup() to perform batch edit
- remove prepareTarget(), this is unneeded since the undoManager can subscribe to notifications (as opposed to the model where you create an undo command and apply it to the document, here the undoManager knows after the fact)
- remove the index parameters to do multiple undos at once etc. this is unnecessary complicating and defcon API doesn't really provide access to undo indexes in the first place. This also avoids making the API biased towards a particular implementation.
Note: I feel like getUndoText()/getRedoText() could be removed since it's primarily for the UI which will probably call the underlying object rather than the defcon API, for now I left it since I don't mind its presence.
r? @anthrotype 
cc @typemytype
=> Improve undo manager API

Lib/defcon/objects/base.py, Lib/defcon/objects/contour.py, Lib/defcon/objects/dataSet.py, Lib/defcon/objects/font.py, Lib/defcon/objects/info.py, Lib/defcon/objects/layer.py, Lib/defcon/tools/notifications.py
BaseObject has a selfNotificationCallback that subscribes to all notifications of the object so to destroy representations. This should be called prior to any specific notification.
Reversing the dispatch order does that.
Note: this still means representations haven't been destroyed in the (None, None) and (None, observableRef) cases, but this change alleviates #102 for the more concrete cases.
r? @anthrotype 
cc @typemytype
=> Notifications: reverse the dispatch order

Lib/defcon/objects/font.py
We also need to bookkeep the dirty flag of font when loading font info, because font info contains the font guidelines (for legacy reasons) which are set on the font object.
Closes trufont/trufont#406.
r? @anthrotype
=> Font: don't set font as dirty when loading guidelines

tools/openClosedUniGenerator.py
This is to address part of the problems in #140 that some open parentheses do not match the closed ones.
These would only leave special exceptions and ornate parentheses (which is because of reversed order in the data) needed to be appended.
=> fix: use close neighbors in openClosedUniGenerator.py

Lib/defcon/objects/layer.py
Before this patch deleted glyphs would load from disk again upon \_\_getitem__ while \_\_contains__ correctly returned False.
Found this bug while working on fontTools.ufoLib.
r? @anthrotype
=> Layer: don't load glyphs that are scheduled for deletion

Lib/defcon/objects/contour.py, Lib/defcon/objects/glyph.py, Lib/defcon/tools/representations.py
This required several other properties and methods. See robofab-developers/fontParts#146 for more background.
=> Implement glyph.correctContourDirection.

Lib/defcon/objects/font.py, Lib/defcon/objects/layerSet.py, Lib/defcon/test/objects/test_font.py, Lib/defcon/test/objects/test_layerSet.py
When saving a UFO (either created from scratch, or loaded from a different path) to the location of an existing UFO, the entire directory needs to be removed before saving the new one.
Fixes googlei18n/fontmake#372
Also, raise a DefconError when attempting to save a new font (i.e. not loaded from disk) without passing 'path' argument to `save()` metohd.
=> fix saving new font or "saving as" to preexisting path

Lib/defcon/objects/base.py, Lib/defcon/test/objects/test_base.py
See #182 for details on why this is needed. This will close #182.
=> Don't store representations in objects without a dispatcher.

Lib/defcon/objects/glyph.py, Lib/defcon/test/objects/test_contour.py
E.g. when the glyph for the Turkish Lira has two identical stroke contours. Seems to not bother Python 2. Fixes https://github.com/typesupply/defcon/issues/197.
=> Fix Glyph.correctContourDirection() crash on Py3 when contours have same area

Lib/defcon/test/objects/test_glyph.py, Lib/defcon/tools/representations.py, appveyor.yml
reported here https://forum.robofont.com/topic/788/rglyph-area-method-only-works-on-glyphs-with-contours/3
=> add glyphset so glyphs with components are also getting an proper area value

Lib/defcon/objects/font.py, Lib/defcon/test/objects/test_font.py, requirements.txt, setup.py
Add `font.ufoFormatVersionTuple` attribute and make `font.ufoFormatVersion` return the major format version again, but deprecate. As per discussion in #289.
=> Fix bw compatibility issue with font.ufoFormatVersion

setup.py
Python 2's pip tries to install it otherwise.
=> Mark library as requiring Python 3.6+

Lib/defcon/objects/glyph.py
initiate methods can receive dict data to set in each intiated object
(this is probably a bug I made in a previous commit)
```
from defcon import Glyph
g = Glyph()
g.name = "bar"
g.appendGuideline(dict(x=10, y=20, identifier="foo"))
data = g.getDataForSerialization()
g.setDataFromSerialization(data)
print(g.identifiers)
```
=> restore identifiers after setDataFromSerialization

Lib/defcon/test/testTools.py, Lib/defcon/test/tools/test_notifications.py, Lib/defcon/tools/notifications.py
=> Dispatcher enhancements

Lib/defcon/test/tools/test_notifications.py, Lib/defcon/tools/notifications.py
The change I made to allow `None` to indicate "please remove everything that observer is watching in observable" had a logic flaw.
- In `addObserver`, `notification=None` means "send every notification to this observer for this observable".
- In `removeObserver`, `notification` means "remove every registered notification from this observable for this observer".
Those seem alike, but this example shows my mistake:
```python
er = This()
able = That()
able.addObserver(observer=er, notification=None, method="anyNotificationHappened")
able.addObserver(observer=er, notification="specific", method="specificNotificationHappened")
able.removeObserver(observer=er, notification=None)
```
The `notification=None` has two conflicting meanings:
1. Remove the notification that will call method …
=> Fix behavior in removeObserver.

.gitignore
otherwise it's listed among untracked files and it may accidentally be committed if one doesn't know that it should not be
=> _version.py is auto-generated, should be git-ignored

Lib/defcon/objects/font.py, Lib/defcon/objects/glyph.py, Lib/defcon/objects/layer.py, Lib/defcon/test/objects/test_font.py, Lib/defcon/test/objects/test_glyph.py, Lib/defcon/test/objects/test_image.py, Lib/defcon/test/objects/test_layer.py
`<font layer glyph>.tempLib` is a lib object to store lib data which is **not** saved into the ufo file, temporary data only available during the life span of the parent object.
Each object which has already an `lib` got a `tempLib`: `font`, `layer` and `glyph`
=> Implementing .tempLib

Lib/defcon/objects/layerSet.py
its possible the reader is already closed and similar to all other stamping callbacks a reader or glyphSet could optionally be provided
=> Add glyphSet argument in _stampLayerInfoDataState

Lib/defcon/test/tools/test_unicodeTools.py
This file does not have executable filesystem permissions, and it does not have script-like content (no `if __name__ == "__main__":` or interesting side-effects).
=> Remove a useless shebang line in a non-executable test script

Lib/defcon/objects/font.py
Before this change, any f.save() would create an empty guidelines array in the fontinfo.plist.
Since guidelines are an optinal attribute, I do not think this is necessary.
=> Do not create empty guidelines array

Lib/defcon/objects/font.py
=> Revert "Do not create empty guidelines array"

Lib/defcon/tools/notifications.py
@typesupply please test before merging...
```py
import defcon 
f = defcon.Font()
names = ["A"]
f.dispatcher.holdNotifications()
for name in names:
f.newGlyph(name) 
f.dispatcher.releaseHeldNotifications()
```
this script throws an error: `defcon/objects/layer.py", line 707, in _glyphNameChange
KeyError: None`
* `layer.newGlyph* [disables all notifications](https://github.com/robotools/defcon/blob/923bd190d85ac3b40915db7dd8b8e1569c4b6771/Lib/defcon/objects/layer.py#L193)
* when looping over all held notifications the disabled one is still there...
--> first loop over all possible combinations and test it against the disabled notifications, if found just return, otherwise look to store them in the held notifications
=> Loop over all possibilities and test if one of them is disabled

Lib/defcon/test/objects/test_dataSet.py, Lib/defcon/test/objects/test_font.py, Lib/defcon/test/objects/test_imageSet.py, Lib/defcon/test/objects/test_layer.py, Lib/defcon/test/objects/test_layerSet.py
we are planning on dropping a hard dependency on `fs` module (pyfilesystem2) in fontTools.ufoLib since it is no longer maintained and is starting to issue a bunch of deprecation warnings (e.g. from pkg_resources scheduled for removal from setuptools in a few months).
I worked on writing a stdlib-only replacement for the subset of classes/functions that ufoLib is currently using here: 
https://github.com/fonttools/fonttools/pull/3885
If one does have `fs` installed, it will still be used for as long as it continues to work (like a "soft" or optional dependency).
Now I noticed defcon's own test suite imports from and calls `fs` methods directly in a bunch of places, that's ok.
However, no matter wheter one is using `fs` directly or its fallback replacement in `fontTools.misc.filesytem`, …
=> simplify use of pyfilesystem2 API in test suite
